spring:
  application:
    name: borsch-srv
  datasource:
    url: jdbc:sqlserver://172.21.10.64\MSSQL19;DatabaseName=BORSCHT
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: test123A#
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    minimumIdle: 1
    maximumPoolSize: 2
server:
  port: 8090
swagger:
  config:
    basePackage: "com.nayax.borsch"
    appName: "application/vnd.borsch.v%s+json"
    title: "Borsch Services API"
    description: "Nayax Borsch Services API v%s"
    version: "0.1"