spring:
  application:
    name: borsch-srv
  datasource:
    url: jdbc:sqlserver://172.21.10.64:1433;DatabaseName=BORSCH
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: username
    password: password
    connectionTimeout: 30000
    idleTimeout: 600000
    maxLifetime: 1800000
    minimumIdle: 1
    maximumPoolSize: 2
server:
  port: 8090
