package com.nayax.borsch.validation.enums;

public enum ValidationAction {

    ADDITIONS_ADD, DRINK_ADD, SIMPLE_PRICE_ITEM_ADD, REMARK_ADD, DISH_ADD,

    ADDITIONS_UPDATE, DRINK_UPDATE, REMARK_UPDATE, DISH_UPDATE,
    ASSORTMENT_UPDATE,

    ADDITIONS_DEL, DRINK_DEL, SIMPLE_PRICE_ITEM_DEL, REMARK_DEL, DISH_DELETE,

    ADDITIONS_GETALL, DRINK_GETALL, REMARK_GETALL, DISH_GETALL,

    USER_ADD_EMAIL,

    PROFILE_ADD, PROFILE_UPDATE, PROFILE_DELETE, PROFILE_GETALL, PROFILE_GET;


    PAGING;
}
